ClientEvents.lang('en_us', e => {
    e.add('kubejs:beastriders', 'Beastriders')
    e.add('kubejs:arcane_ascension', 'Arcane Ascension')
    e.add('kubejs:ironclad', 'Ironclad')
    e.add('kubejs:arachnophobia', 'Arachnophobia')
    e.add('kubejs:monstrosities', 'Monstrosities')
    e.add('kubejs:ravenous_horde', 'Ravenous Horde')
    e.add('kubejs:undead_feast', 'Undead Feast')
    e.add('kubejs:icebound', 'Icebound')
    e.add('kubejs:death_snare', 'Death Snare')
    e.add('kubejs:piglin_rage', 'Piglin Rage')
    e.add('kubejs:brute_force', 'Brute Force')
    e.add('kubejs:tempestborn', 'Tempestborn')
    e.add('kubejs:vexsplosion', 'Vexsplosion')
    e.add('kubejs:shroudwalkers', 'Shroudwalkers')
    e.add('kubejs:corrupted_kin', 'Corrupted Kin')
    e.add('kubejs:veiled_broodlings', 'Veiled Broodlings')
    e.add('kubejs:deep_abyss', 'Deep Abyss')
    e.add('kubejs:mob_menagerie', 'Mob Menagerie')
    //e.add('kubejs:eyes_within_the_stone', 'Eyes Within The Stone')
    e.add('kubejs:screeching_shadows', 'Screeching Shadows')
    e.add('kubejs:event_horizon', 'Event Horizon')
    e.add('kubejs:weeping_fate', 'Weeping Fate')
    e.add('kubejs:unending_horde', 'Unending Horde')
    e.add('kubejs:critical_mass', 'Critical Mass')
    e.add('kubejs:bone_brigade', 'Bone Brigade')
    e.add('kubejs:blood_moon', 'Blood Moon')
    e.add('kubejs:glass_bones', 'Glass Bones')
    e.add('kubejs:pyromania', 'Pyromania')
    e.add('kubejs:glancing_blows', 'Glancing Blows')
  })
  

